config/routes.rb
ScratchPad::Application.routes.draw do
  root 'notes#index'

  resources :notes, only: [:index, :show]
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	# make these methods available in the view; making queries so these methods
	# belong in the controller
	helper_method :notes, :note

	def notes
		@_notes ||= Note.all
	end

	def note
		@_note ||= notes.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScratchPad</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<%= yield %>
</div>

</body>
</html>

app/views/notes/index.html.erb
<ul>
	<% notes.each do |note| %>
		<li>
			<dl>
				<dt>Title</dt>
				<dd><%= link_to note.title, note %></dd>
				<dt>Content</dt>
				<dd><%= note.content %></dd>
			</dl>
		</li>
	<% end %>
</ul>

app/views/notes/show.html.erb
<h1><%= note.title %></h1>
<p><%= note.content %></p>
<%= link_to "Back", notes_path %>